### ISSUE TITLE
use target_link_libraries in CMakeLists.txt

### ISSUE THREAD

**Issue by adamsj-ros** [oci-labs/rmw_opendds#7]
I can't comment on it directly because it's not near something being changed, but these lines:

https://github.com/oci-labs/rmw_opendds/blob/920e07a437224751f357824ab1146b42073a62c8/rmw_opendds_cpp/CMakeLists.txt#L77-L78

should be replace by one or more `target_link_libraries` on the appropriate OpenDDS libraries that need to be used. There is an example of this in [this CMakelists file](https://github.com/objectcomputing/OpenDDS/blob/master/DevGuideExamples/DCPS/Messenger/CMakeLists.txt).

_Originally posted by @iguessthislldo in https://github.com/oci-labs/rmw_opendds/pull/6#issuecomment-570438770_

**Comment by adamsj-ros** [comment]
@kuznetsovmoci , I'm not sure we took this approach. Did you discuss this with @iguessthislldo? I don't see this suggestion implemented in `rmw_opendds_cpp/CMakeLists.txt`.

**Comment by kuznetsovmoci** [comment]
@adamsj-oci : I have implemented it as Fred suggested. We almost have no other choice, as we implement 'new' CMake API. I think you may be following the link in the discussion, which still points to the original (old) version of the file. Let me know if I am missing something. Otherwise it looks like this issue can be closed.
